<a href="https://colab.research.google.com/github/luisfernandorutti43-wq/eje/blob/main/ejercicio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy, ciencia de datos

In [1]:
import numpy as np


In [2]:
#dimension 1
array_id=np.array({10,20,30})
print(array_id)

{10, 20, 30}


In [3]:
array_id

array({10, 20, 30}, dtype=object)

Dimension 2 arrays


In [4]:
array_2id=np.array([(10,20,30),(50,60,70)])
array_2id

array([[10, 20, 30],
       [50, 60, 70]])

Dimension 3 arrays

In [5]:
array_3id=np.array([(10,20,30),(40,50,60),(70,80,90)],dtype=float)
array_3id


array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

array con ceros de filas y 4  columnas


In [6]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array dr unos con 2 dimensiones 4 filas 5 columnas

In [7]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

arrays intervalos y saltos

In [8]:
np.arange(20,30,40)

array([20])

In [9]:
np.arange(11,50,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

In [10]:
edadmenor = 15
edadmayor = 30
mayor = np.maximum (edadmenor,edadmayor)
menor = np.minimum (edadmenor,edadmayor)

print("el mayor es: " ,mayor)
print("el menor es: " ,menor)

el mayor es:  30
el menor es:  15


In [11]:
#ARRAYS CON INTERVALO Y DIVISIONES
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAYS CON VALORES DADOS

In [15]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

array matrix identidad, diogonal, de unos

In [14]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3,3,1,)

In [ ]:
np.random.random((4,4))

Array de numeros vacios 4*3

grabar y cargar

In [ ]:
np.save('mi_arrays_3d',np.random.random((3,3)))



In [ ]:
#cargar
mi_arrays=np.load('mi_arrays_3d.npy')
mi_arrays


grabar  y cargar ficheros de texto


In [ ]:
# Crear un array de ejemplo
array_2id = np.eye(6)  # matriz identidad 6x6

# Guardar en archivo de texto
np.savetxt('mi_array.txt', array_2id, delimiter=" ")

In [ ]:
# Cargar el archivo
array_cargado = np.loadtxt('mi_array.txt')

print(array_cargado)

almacen de materias

In [ ]:
materias = np.array(' Matemáticas, Física, Química, Historia,Lengua')
print (materias)

np.save('materias',materias)


EJERCICIO 2

In [ ]:
materias= [ "Matemáticas", "Física", "Química", "Historia","Lengua"]


for materia in materias:

  print(f"yo estudio {materia}")
np.save('eje2materias', materias)

EJERCICIO 3

In [ ]:
# Lista de asignaturas
materias = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]

# Lista para guardar las notas
notas = []

# Pedir al usuario la nota de cada asignatura

for materia in materias:
    while True:
        try:
            nota = float(input(f"Introduce la nota de {materia}: "))
            if 0 <= nota <= 20:
                notas.append(nota)
                break
            else:
                print("Por favor, introduce una nota entre 0 y 20.")
        except ValueError:
            print("Por favor, introduce un número válido.")

# Mostrar las asignaturas con sus notas
for asignatura, nota in zip(materias, notas):
    print(f"En {asignatura} has sacado {nota}")


np.save('eje3materias',materias)




EJERCICIO 4


In [18]:

# Lista para almacenar los números ganadores
ganadores = []

# Preguntar al usuario 3 números ganadores
print("Introduce los 3 números ganadores de la lotería primitiva:")

while len(ganadores) < 3:
    try:
        num = int(input(f"Número {len(ganadores)+1}: "))
        if 1 <= num <= 10:  # rango típico para la lotería primitiva
            if num not in ganadores:
                ganadores.append(num)
            else:
                print("Ese número ya lo has introducido, prueba con otro.")
        else:
            print("Introduce un número entre 1 y 10.")
    except ValueError:
        print("Por favor, introduce un número entero válido.")

# Ordenar la lista de menor a mayor
ganadores.sort()

# Mostrar los números ordenados
print("Los números ganadores ordenados son:")
print(ganadores)
np.save('eje4',ganadores)

Introduce los 3 números ganadores de la lotería primitiva:


KeyboardInterrupt: Interrupted by user

EJERCICIO 5

In [16]:
numeros=[1,2,3,4,5,6,7,8,9,10]
numeros_inverso =numeros [-1]
print (numeros_inverso)


10


In [20]:
#ENTEROS
np.int64

numpy.int64

In [21]:
#decimal, flotantes
np.float64

numpy.float64

In [22]:
#complejos
np.complex64

numpy.complex64

In [ ]:
#booleanos
np.bool
np-np.bool_

In [25]:
#objectos
np.object_

numpy.object_

In [23]:
#cadena de texto
np.strings

<module 'numpy.strings' from '/usr/local/lib/python3.11/dist-packages/numpy/strings/__init__.py'>

In [24]:
np.bytes_

numpy.bytes_

In [ ]:
#datos que no se usa
np.unicode

propiedades y caractericas de enteros

In [32]:
array_3id

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [29]:
#ver la dimension de las  filas y columnas
array_2id.shape

(2, 3)

In [ ]:
# contando la longitud  longitud el mayor de un array
len(array_3id)

In [34]:
#numero de dimensiones
array_2id.ndim

2

In [49]:
array_5id = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 101, 102], [100, 101, 102]], ndmin=5)
print(array_5id)
print("Dimensiones:", array_5id.ndim)

[[[[[ 10  20  30]
    [ 40  50  60]
    [ 70  80  90]
    [100 101 102]
    [100 101 102]]]]]
Dimensiones: 5


In [43]:
array_5id.ndim

AttributeError: 'tuple' object has no attribute 'ndim'

In [51]:
array_3id.dtype.name

'float64'

In [53]:
array_5id.astype(np.float16)

array([[[[[ 10.,  20.,  30.],
          [ 40.,  50.,  60.],
          [ 70.,  80.,  90.],
          [100., 101., 102.],
          [100., 101., 102.]]]]], dtype=float16)

In [55]:
array_5id.astype(str)

array([[[[['10', '20', '30'],
          ['40', '50', '60'],
          ['70', '80', '90'],
          ['100', '101', '102'],
          ['100', '101', '102']]]]], dtype='<U21')

operaciones matematicos

In [74]:
#array de ejmplo
array4=np.random.random((4,4,2))
array4

array([[[0.75354173, 0.57653602],
        [0.03315195, 0.75345006],
        [0.14776204, 0.70070125],
        [0.39942277, 0.33407931]],

       [[0.84246244, 0.34977379],
        [0.05766964, 0.47102173],
        [0.88361159, 0.70401634],
        [0.49350164, 0.64768469]],

       [[0.76026496, 0.74582354],
        [0.11577004, 0.96981865],
        [0.90660319, 0.69006394],
        [0.78365851, 0.37230127]],

       [[0.87552652, 0.4263565 ],
        [0.17915313, 0.66016613],
        [0.51193134, 0.71974561],
        [0.0524705 , 0.94676733]]])

In [75]:
#array
array5=np.random.random((4,4,2))
array5

array([[[0.32014441, 0.31049068],
        [0.76627258, 0.38269337],
        [0.76389063, 0.09530723],
        [0.7087377 , 0.83167038]],

       [[0.90932793, 0.09109706],
        [0.95998038, 0.40150877],
        [0.27396766, 0.21196242],
        [0.01230642, 0.5333484 ]],

       [[0.68064765, 0.02707434],
        [0.11257245, 0.97217024],
        [0.57601404, 0.22354407],
        [0.11633941, 0.21389777]],

       [[0.56726508, 0.12385118],
        [0.76256816, 0.76298772],
        [0.23677032, 0.65547857],
        [0.48099388, 0.59559877]]])

In [77]:
array3=np.random.random((4,4,2))


In [76]:
#suma
array6=array3+array4+array5
array4

array([[[0.75354173, 0.57653602],
        [0.03315195, 0.75345006],
        [0.14776204, 0.70070125],
        [0.39942277, 0.33407931]],

       [[0.84246244, 0.34977379],
        [0.05766964, 0.47102173],
        [0.88361159, 0.70401634],
        [0.49350164, 0.64768469]],

       [[0.76026496, 0.74582354],
        [0.11577004, 0.96981865],
        [0.90660319, 0.69006394],
        [0.78365851, 0.37230127]],

       [[0.87552652, 0.4263565 ],
        [0.17915313, 0.66016613],
        [0.51193134, 0.71974561],
        [0.0524705 , 0.94676733]]])

In [78]:
#orta frma para sumar
array7=np.add(array3,array4,array5)
array7

array([[[1.03239976, 0.70677525],
        [0.27161789, 1.30621077],
        [0.39411109, 1.21382532],
        [1.02006277, 0.56655419]],

       [[1.12097529, 0.45858753],
        [0.44567156, 0.88009643],
        [1.5747275 , 1.64036233],
        [1.08240607, 0.72068813]],

       [[1.48205897, 0.82930916],
        [0.30787116, 1.84874804],
        [1.86371204, 1.67158351],
        [1.74951121, 0.97190012]],

       [[0.90014274, 0.54451308],
        [0.65142172, 1.12171524],
        [1.20198859, 1.5065948 ],
        [0.39159389, 1.74611784]]])

In [79]:
#resta
array8=array7-array6
array8

array([[[-0.05407254, -0.88447434],
        [-0.59833201,  0.16843533],
        [-1.01829065,  0.23994682],
        [-0.69992127, -1.50354981]],

       [[-1.01052232, -0.81898755],
        [-1.42908164, -0.54440616],
        [ 0.23859217,  0.09916537],
        [ 0.49326564, -1.40680625]],

       [[-0.26291776, -0.58311992],
        [-0.50376832, -0.17044116],
        [-0.37865955,  0.51023321],
        [-0.08668471, -0.26996389]],

       [[-0.99533683, -0.91013321],
        [-1.22991568, -1.06307083],
        [ 0.41736969, -0.3982297 ],
        [-1.08590592, -0.35821859]]])

In [80]:
#multiplicacion
array9=np.multiply(array8,array4)
array9

array([[[-0.04074591, -0.50993132],
        [-0.01983587,  0.12690761],
        [-0.15046471,  0.16813104],
        [-0.27956449, -0.50230487]],

       [[-0.8513271 , -0.28646038],
        [-0.08241462, -0.25642713],
        [ 0.21082281,  0.06981404],
        [ 0.2434274 , -0.91116687]],

       [[-0.19988716, -0.43490456],
        [-0.05832128, -0.16529701],
        [-0.34329395,  0.35209354],
        [-0.06793121, -0.1005079 ]],

       [[-0.87144379, -0.38804121],
        [-0.22034324, -0.70180335],
        [ 0.21366462, -0.28662408],
        [-0.05697803, -0.33914966]]])

In [82]:
#resta con funcion
array10=np.subtract
#division
array11=np.divide(array7,array8)
array11

array([[[-19.09286629,  -0.79909073],
        [ -0.45395847,   7.75496926],
        [ -0.38703202,   5.05872644],
        [ -1.45739645,  -0.37681106]],

       [[ -1.10930285,  -0.55994445],
        [ -0.31185872,  -1.61661733],
        [  6.60008035,  16.54168588],
        [  2.19436747,  -0.51228669]],

       [[ -5.63696785,  -1.42219315],
        [ -0.6111364 , -10.84684051],
        [ -4.92186731,   3.27611663],
        [-20.18246646,  -3.60011158]],

       [[ -0.90435992,  -0.59827844],
        [ -0.52964746,  -1.0551651 ],
        [  2.87991348,  -3.78323061],
        [ -0.36061493,  -4.87444779]]])

In [83]:
#exponente
np.exp(array3)

array([[[1.3216197 , 1.13910085],
        [1.26930047, 1.73804464],
        [1.27934605, 1.67050183],
        [1.86011815, 1.26171876]],

       [[1.32116358, 1.11495465],
        [1.47403262, 1.50542417],
        [1.99594159, 2.55064431],
        [1.80201311, 1.07573424]],

       [[2.05812219, 1.08706959],
        [1.21179305, 2.40831994],
        [2.60415658, 2.66850815],
        [2.62702679, 1.82138801]],

       [[1.0249217 , 1.12542031],
        [1.60362804, 1.58652979],
        [1.99382967, 2.19646486],
        [1.40371654, 2.22409592]]])

In [ ]:
#seno
np.sin(array5)
#coseno
np.cos(array6)
#logaritmo
np.log(array3)


COMPARACIONES ENTRE MATRICES

In [84]:
#==
array4==array3

array([[[False, False],
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        [False, False]]])

In [87]:
#<
array11 < 0.5

array([[[ True,  True],
        [ True, False],
        [ True, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [False, False],
        [False,  True]],

       [[ True,  True],
        [ True,  True],
        [ True, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [False,  True],
        [ True,  True]]])

In [88]:
#>
array11 > 0.5

array([[[False, False],
        [False,  True],
        [False,  True],
        [False, False]],

       [[False, False],
        [False, False],
        [ True,  True],
        [ True, False]],

       [[False, False],
        [False, False],
        [False,  True],
        [False, False]],

       [[False, False],
        [False, False],
        [ True, False],
        [False, False]]])

In [89]:
#<=  /  >=
array8<=0.1

array([[[ True,  True],
        [ True, False],
        [ True, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [False,  True],
        [False,  True]],

       [[ True,  True],
        [ True,  True],
        [ True, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [False,  True],
        [ True,  True]]])

ESTADISTICAS  Y FUNCIONES

In [92]:
array1 =np.random.random((5,5,))
array1

array([[0.33269999, 0.38702922, 0.73605048, 0.31403313, 0.55078243],
       [0.87223171, 0.52344602, 0.7477825 , 0.6831739 , 0.94307531],
       [0.30667063, 0.63091583, 0.3585126 , 0.43443847, 0.4917522 ],
       [0.04881734, 0.47951702, 0.65349701, 0.93233672, 0.29698554],
       [0.27761291, 0.86975706, 0.10974581, 0.04341164, 0.0551592 ]])

In [93]:
#SUMA
suma_total=array4.sum()
print(suma_total)

17.864808117850863


In [95]:
#valor minino - maximo
array6.max()
array6.min()

np.float64(0.5891404329839509)

In [97]:
#maximo por la fila
array6.max(axis=1)

array([[1.71998404, 2.070104  ],
       [2.13149761, 2.12749438],
       [2.24237159, 2.0191892 ],
       [1.89547957, 2.18478606]])

In [99]:
#fila acumulada
array7.comsum(axis=1)

AttributeError: 'numpy.ndarray' object has no attribute 'comsum'