<a href="https://colab.research.google.com/github/luisfernandorutti43-wq/eje/blob/main/1/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy, ciencia de datos

In [ ]:
import numpy as np


In [ ]:
#dimension 1
array_id=np.array({10,20,30})
print(array_id)

{10, 20, 30}


In [ ]:
array_id

array({10, 20, 30}, dtype=object)

Dimension 2 arrays


In [ ]:
array_2id=np.array([(10,20,30),(50,60,70)])
array_2id

array([[10, 20, 30],
       [50, 60, 70]])

Dimension 3 arrays

In [ ]:
array_3id=np.array([(10,20,30),(40,50,60),(70,80,90)],dtype=float)
array_3id


array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

array con ceros de filas y 4  columnas


In [ ]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array dr unos con 2 dimensiones 4 filas 5 columnas

In [ ]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

arrays intervalos y saltos

In [ ]:
np.arange(20,30,40)

array([20])

In [ ]:
np.arange(11,50,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

In [ ]:
edadmenor = 15
edadmayor = 30
mayor = np.maximum (edadmenor,edadmayor)
menor = np.minimum (edadmenor,edadmayor)

print("el mayor es: " ,mayor)
print("el menor es: " ,menor)

el mayor es:  30
el menor es:  15


In [ ]:
#ARRAYS CON INTERVALO Y DIVISIONES
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAYS CON VALORES DADOS

In [ ]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
array matrix identidad, diogonal, de unos

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3,3,1,)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
np.random.random((4,4))

array([[0.9281473 , 0.35996282, 0.04970127, 0.81230517],
       [0.28332216, 0.26177808, 0.91460654, 0.50577643],
       [0.55151189, 0.96568202, 0.81786696, 0.26805557],
       [0.92925651, 0.99427875, 0.05474503, 0.06721785]])

Array de numeros vacios 4*3

grabar y cargar

In [ ]:
np.save('mi_arrays_3d',np.random.random((3,3)))



In [ ]:
#cargar
mi_arrays=np.load('mi_arrays_3d.npy')
mi_arrays

array([[0.8486208 , 0.87753709, 0.30892217],
       [0.68897478, 0.69809836, 0.36378371],
       [0.96218438, 0.89693034, 0.71895882]])


grabar  y cargar ficheros de texto


In [ ]:
# Crear un array de ejemplo
array_2id = np.eye(6)  # matriz identidad 6x6

# Guardar en archivo de texto
np.savetxt('mi_array.txt', array_2id, delimiter=" ")

In [ ]:
# Cargar el archivo
array_cargado = np.loadtxt('mi_array.txt')

print(array_cargado)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


almacen de materias

In [ ]:
materias = np.array(' Matemáticas, Física, Química, Historia,Lengua')
print (materias)

np.save('materias',materias)


 Matemáticas, Física, Química, Historia,Lengua


EJERCICIO 2

In [ ]:
materias= [ "Matemáticas", "Física", "Química", "Historia","Lengua"]


for materia in materias:

  print(f"yo estudio {materia}")
np.save('eje2materias', materias)

yo estudio Matemáticas
yo estudio Física
yo estudio Química
yo estudio Historia
yo estudio Lengua


EJERCICIO 3

In [ ]:
# Lista de asignaturas
materias = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]

# Lista para guardar las notas
notas = []

# Pedir al usuario la nota de cada asignatura

for materia in materias:
    while True:
        try:
            nota = float(input(f"Introduce la nota de {materia}: "))
            if 0 <= nota <= 20:
                notas.append(nota)
                break
            else:
                print("Por favor, introduce una nota entre 0 y 20.")
        except ValueError:
            print("Por favor, introduce un número válido.")

# Mostrar las asignaturas con sus notas
for asignatura, nota in zip(materias, notas):
    print(f"En {asignatura} has sacado {nota}")


np.save('eje3materias',materias)




Introduce la nota de Matemáticas: 0
Introduce la nota de Física: 0
Introduce la nota de Química: 0
Introduce la nota de Historia: 0
Introduce la nota de Lengua: 0
En Matemáticas has sacado 0.0
En Física has sacado 0.0
En Química has sacado 0.0
En Historia has sacado 0.0
En Lengua has sacado 0.0


EJERCICIO 4


In [ ]:

# Lista para almacenar los números ganadores
ganadores = []

# Preguntar al usuario 3 números ganadores
print("Introduce los 3 números ganadores de la lotería primitiva:")

while len(ganadores) < 3:
    try:
        num = int(input(f"Número {len(ganadores)+1}: "))
        if 1 <= num <= 10:  # rango típico para la lotería primitiva
            if num not in ganadores:
                ganadores.append(num)
            else:
                print("Ese número ya lo has introducido, prueba con otro.")
        else:
            print("Introduce un número entre 1 y 10.")
    except ValueError:
        print("Por favor, introduce un número entero válido.")

# Ordenar la lista de menor a mayor
ganadores.sort()

# Mostrar los números ordenados
print("Los números ganadores ordenados son:")
print(ganadores)
np.save('eje4',ganadores)

Introduce los 3 números ganadores de la lotería primitiva:
Número 1: 0
Introduce un número entre 1 y 10.
Número 1: 1
Número 2: 2
Número 3: 3
Los números ganadores ordenados son:
[1, 2, 3]


EJERCICIO 5

In [ ]:
numeros=[1,2,3,4,5,6,7,8,9,10]
numeros_inverso =numeros [-1]
print (numeros_inverso)


10
